export const items: {[key: string]: string} = {
    definition: "定義", 
    synonyms: "類義語", 
    antonyms: "対義語",
    examples: "例文",
    typeOf: "一般化",
    hasTypes: "具体化",
    partOf: "部分",
    hasParts: "部品",
    instanceOf: "一例",
    hasInstances: "一例",
    similarTo: "関連単語",
    also: "イディオム",
    entails: "示唆",
    memberOf: "属性",
    hasMembers: "属性",
    substanceOf: "含まれる物質",
    hasSubstances: "含まれる物質",
    inCategory: "カテゴリ",
    hasCategories: "カテゴリ",
    usageOf: "使用例",
    hasUsages: "使用例",
    inRegion: "地域",
    regionOf: "地域",
    pertainsTo: "関連語",
    partOfSpeech: "品詞",
};

export const gets: string[] = [
    "definition",
    "synonyms",
    "antonyms",
    "examples",
    "typeOf",
    "hasTypes",
    "partOf",
    "hasParts",
    "instanceOf",
    "hasInstances",
    "similarTo",
    "also",
    "entails",
    "memberOf",
    "hasMembers",
    "substanceOf", 
    "hasSubstances",
    "inCategory",
    "hasCategories",
    "usageOf",
    "hasUsages",
    "inRegion",
    "regionOf",
    "pertainsTo",
    "partOfSpeech",
];